######################################################################
# Automatically generated by qmake (2.01a) Thu May 16 11:28:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
