######################################################################
# Automatically generated by qmake (2.01a) Fri May 24 19:06:54 2013
######################################################################

SOURCES -= test*
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PacketConsumerThread.h PacketPool.h PacketProducerThread.h
SOURCES += PacketConsumerThread.cpp \
           PacketPool.cpp \
           PacketProducerThread.cpp \
           test.cpp
